version: "3.8"
services:
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - ./database:/data/db
        networks:
            - backend
        restart: always

    mongo-express:
        image: mongo-express:latest
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        networks:
            - backend
        restart: always

    backend:
        build:
            context: ./backend
            cache_from: []
        env_file:
            - ./backend/.env
        environment:
            PORT: ${PORT}
            MONGODB_URI: ${MONGODB_URI}
            JWT_SECRET: ${JWT_SECRET}
            NODE_ENV: ${NODE_ENV}
            ORIGIN: ${ORIGIN}
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        networks:
            - backend
        restart: always

    frontend:
        build:
            context: ./frontend
            cache_from: []
        env_file:
            - ./frontend/.env
        environment:
            VITE_PORT: ${VITE_PORT}
            VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - backend
        restart: always

networks:
    backend:
        driver: bridge
