version: "3.8"
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - ./database:/data/db
        networks:
            - backend
        restart: always

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        networks:
            - backend
        restart: always

    backend:
        build: ./backend
        container_name: backend
        env_file:
            - ./backend/.env
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        networks:
            - backend
        restart: always

    frontend:
        build: ./frontend
        container_name: frontend
        env_file:
            - ./frontend/.env
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - backend
        restart: always

networks:
    backend:
        driver: bridge
